# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 11:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
                ('Comments', models.TextField()),
                ('Created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
