# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fb',
            old_name='Comments',
            new_name='Comment',
        ),
    ]
