# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedback', '0002_auto_20170222_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fb',
            name='Comment',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='fb',
            name='Name',
            field=models.CharField(help_text='max. 50 characters', max_length=50),
        ),
    ]
